### PR TITLE
More flexible package.path modification to support local or forked repositories.

### PR DESCRIPTION
**Pull request by khsoh**
The change was inspired by : https://github.com/mikkasendke/sessionizer.wezterm/commit/1260fb36a1b87b53839b4d75e834545ca5acef22

### CODE REVIEW

**Comment by michaelbrusegard** [comment]
Does it work on all operation systems?

**Comment by khsoh** [comment]
I have only tested this on macOS.

**Comment by michaelbrusegard** [comment]
Lets wait for this to be tested by someone who has windows before merging

**Comment by 0xJWLabs** [comment]
Doesn't work for me. On windows 11 and get tabline.config not found

**Comment by michaelbrusegard** [comment]
@khsoh Windows uses backslashes for paths so you have to check if it is windows and then use backslashes

**Comment by khsoh** [comment]
@michaelbrusegard - sorry - but I do not have a Windows machine to try this out.  The code I have changed only changes `package.path` without inserting any new separator.

So, **if** `package.path` is defined in a system-specific way, it should have been by default been generated with backslashes for Windows.  But I do not have a WIndows machine to verify how `package.path` would look like.

**Comment by michaelbrusegard** [comment]
@khsoh I understand, we can wait until someone that can test on windows finds a solution

**Comment by michaelbrusegard** [comment]
I will close this as it did not seem to work on windows. I provided a simple solution with the http path strings included

**Pull request closed without merging**
